### ISSUE TITLE
Put commas in numbers

### ISSUE THREAD

**Issue by yen3** [gugod/taiwan-covid19-vaccination-progress-bot#1]
Thanks for the useful bot. For readability, is it possible to add commas in numbers?

For example:
"10000000" => "10,000,000"

Since I am unfamiliar with perl, I am sorry that I could not send the pull request. How do you think about the feature?

Thanks for your reading.

**Comment by gugod** [comment]
Here we go: https://github.com/gugod/taiwan-covid19-vaccination-progress-bot/commit/9e57684912af25db617ef497349afdf0f514656d

**Comment by yen3** [comment]
Thanks for your prompt help!
