### ISSUE TITLE
關於劑次人口比問題

### ISSUE THREAD

**Issue by walishcs** [gugod/taiwan-covid19-vaccination-progress-bot#2]
開發者您好，本日指揮中心宣布將會更改統計方式為劑次人口比，不曉得有沒有機會加上此數據，感謝您的貢獻！

**Comment by gugod** [comment]
這 bot 並不是直接去取指揮中心的 pdf ​，而是 owid/covid-19-data 轉換好的 CSV 檔： https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Taiwan.csv

因此沒有直接就包含劑次人口比。但我們可手動計算。以 9/14 的資料為例，取八月份人口統計結果 23451837，四捨五入至小數點以下第二位， 算的的數字與指揮中心提供的數字相同：

```
累計至 2021-09-13，全民共接種了 12,488,096 劑，劑次人口比 53.25  (劑/每百人)。

💉第一劑 11,433,445 (+16,901)
[############______________] 48.752%

💉第二劑 1,054,651 (+8,003)
[#_________________________] 4.497%

#CovidVaccine #COVID19 #COVID19Taiwan
```

**Comment by gugod** [comment]
Done. commit: 7f7c90fc33675217c19284f81904dfe4187c9b80
